apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
data:
  DB_DATABASE_NAME: immich
  DB_USERNAME: postgres
  IMMICH_VERSION: release
  REDIS_PORT: "6379"
  PGDATA: /var/lib/postgresql/pgdata/data
